name: spacetime
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.9
  - pip
  - jupyter
  - jupyterlab
  - pytorch
  - transformers
  - pandas
  - numpy
  - matplotlib
  - omegaconf
  - einops
  - opt_einsum
  - tqdm
  - rich
  - wandb
  #- timm=0.4.12