blocks:
- input_dim: 128
  pre_config: 'ssm/preprocess/residual'
  ssm_config: 'ssm/companion'
  mlp_config: 'mlp/default'
- input_dim: 128
  pre_config: 'ssm/preprocess/none'
  ssm_config: 'ssm/companion'
  mlp_config: 'mlp/default'
- input_dim: 128
  pre_config: 'ssm/preprocess/none'
  ssm_config: 'ssm/companion'
  mlp_config: 'mlp/default'